name: AWIIN
favicon: null
layout_spectrum: 0.24323
typography_spectrum: 0.47374
title: DJ AWIIN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#686765'
    - '#f22942'
    - '#60f80d'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
