name: AWIIN
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15104
title: DJ AWIIN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#42488d'
    - '#9dc3f8'
    - '#f08045'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
