name: AWIIN
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47374
title: DJ AWIIN
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#df070b'
    - '#069d04'
    - '#f3c913'
    - '#fc6df7'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
